const headphonesList = [
  {
    id: 1,
    name: 'AirPods Pro',
    price: 49.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_a_4_a1zwtv.webp',
  },
  {
    id: 2,
    name: 'Sony WH-10',
    price: 59.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_b_4_j4o9ly.webp',
  },
  {
    id: 3,
    name: 'Bose  35 II',
    price: 39.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_a_3_inzztb.webp',
  },
  {
    id: 4,
    name: 'Beats Studio3 ',
    price: 69.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_b_1_lfafdd.webp',
  },
  {
    id: 5,
    name: 'Sennheiser less',
    price: 79.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_c_2_xgzivn.webp',
  },
  {
    id: 6,
    name: 'Beats Solo Pro',
    price: 49.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_b_2_pcjguw.webp',
  },
  {
    id: 7,
    name: 'Sony WH-C10N',
    price: 59.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245861/FOOD_APP/HEADPHONE/headphones_c_1_xgnsry.webp',
  },
  {
    id: 8,
    name: 'Bose Nois7t5',
    price: 89.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245862/FOOD_APP/HEADPHONE/headphones_a_2_rdmxgj.webp',
  },
  {
    id: 9,
    name: 'Sennheiser  S',
    price: 99.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245862/FOOD_APP/HEADPHONE/headphones_c_4_pasbla.webp',
  },
  {
    id: 10,
    name: 'Apple EarPods',
    price: 29.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245862/FOOD_APP/HEADPHONE/earphones_a_2_yvsw8v.webp',
  },
  {
    id: 11,
    name: 'JBL Free X',
    price: 59.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245862/FOOD_APP/HEADPHONE/headphones_c_3_pscwv7.webp',
  },
  {
    id: 12,
    name: 'Galaxy Buds',
    price: 39.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245862/FOOD_APP/HEADPHONE/earphones_a_1_objrug.webp',
  },
  {
    id: 13,
    name: 'BSoundSport',
    price: 49.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245863/FOOD_APP/HEADPHONE/earphones_c_2_tsgszk.webp',
  },
  {
    id: 14,
    name: 'Jabra Elite 75t',
    price: 34.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245863/FOOD_APP/HEADPHONE/earphones_b_2_frp14b.webp',
  },
  {
    id: 15,
    name: 'Beats Power',
    price: 79.99,
    inStock: true,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245863/FOOD_APP/HEADPHONE/headphones_b_3_aeymlf.webp',
  },
  {
    id: 16,
    name: 'Anker Score ',
    price: 44.99,
    inStock: false,
    imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245863/FOOD_APP/HEADPHONE/earphones_b_3_ici0wk.webp',
  },
  // {
  //   id: 17,
  //   name: '1MORE Stylish True Wireless Earbuds',
  //   price: 59.99,
  //   inStock: true,
  //   imgUrl: 'https://res.cloudinary.com/durbee4ln/image/upload/v1703245883/FOOD_APP/HEADPHONE/earphones_a_3_ltzalb.webp',
  // },
];

export default headphonesList;
